/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author bloqu
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtInicioUsuario = new javax.swing.JTextField();
        txtInicioContrasena = new javax.swing.JTextField();
        cbInicioTipoUsuario = new javax.swing.JComboBox<>();
        btnInicioIniciarSesion = new javax.swing.JButton();
        btnInicioLimpiar = new javax.swing.JButton();
        btnInicioRegistrarse = new javax.swing.JButton();
        btnInicioSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("INICIO DE SESIÓN");

        jLabel3.setText("Usuario");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Tipo de usuario");

        cbInicioTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Usuario", "Moderador" }));
        cbInicioTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInicioTipoUsuarioActionPerformed(evt);
            }
        });

        btnInicioIniciarSesion.setText("Iniciar sesión");
        btnInicioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioIniciarSesionActionPerformed(evt);
            }
        });

        btnInicioLimpiar.setText("Limpiar");
        btnInicioLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLimpiarActionPerformed(evt);
            }
        });

        btnInicioRegistrarse.setText("Registrarse");
        btnInicioRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioRegistrarseActionPerformed(evt);
            }
        });

        btnInicioSalir.setText("Salir");
        btnInicioSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbInicioTipoUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtInicioContrasena, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtInicioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnInicioLimpiar)
                            .addGap(18, 18, 18)
                            .addComponent(btnInicioIniciarSesion)
                            .addGap(18, 18, 18)
                            .addComponent(btnInicioRegistrarse))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(47, 47, 47)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInicioSalir)
                        .addGap(118, 118, 118)))
                .addGap(415, 415, 415))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtInicioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtInicioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbInicioTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInicioIniciarSesion)
                            .addComponent(btnInicioRegistrarse)
                            .addComponent(btnInicioLimpiar))
                        .addGap(18, 18, 18)
                        .addComponent(btnInicioSalir)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(381, 335));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbInicioTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInicioTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInicioTipoUsuarioActionPerformed

    private void btnInicioLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLimpiarActionPerformed
        txtInicioUsuario.setText("");
        txtInicioContrasena.setText("");
        cbInicioTipoUsuario.setSelectedIndex(0);
    }//GEN-LAST:event_btnInicioLimpiarActionPerformed

    private void btnInicioSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSalirActionPerformed
        int rpta=JOptionPane.showOptionDialog(this,"¿Estas seguro de salir?","Mensaje de confirmación",
                                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,
                                    null,null);
        if(rpta==0)
            System.exit(0);
    }//GEN-LAST:event_btnInicioSalirActionPerformed

    private void btnInicioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioIniciarSesionActionPerformed
    String usuarioIngresado = txtInicioUsuario.getText();
    String contrasenaIngresada = txtInicioContrasena.getText();
    String tipoUsuarioIngresado = cbInicioTipoUsuario.getSelectedItem().toString();

    ManejoArchivosTXT manejoArchivos = new ManejoArchivosTXT();
    
    boolean logeado = false;

    for (Usuario user : manejoArchivos.usuarios) { 
        if (user.getUsuario().equals(usuarioIngresado) && 
            user.getContrasena().equals(contrasenaIngresada) && 
            user.getTipoUsuario().equals(tipoUsuarioIngresado)) {
            logeado = true;
            break;
        }
    }

    if (logeado) {
        frmUsuarioUI newFrame = new frmUsuarioUI();
        newFrame.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Los datos son incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnInicioIniciarSesionActionPerformed

    private void btnInicioRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioRegistrarseActionPerformed
        frmRegistroUsuario newFrame = new frmRegistroUsuario();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioIniciarSesion;
    private javax.swing.JButton btnInicioLimpiar;
    private javax.swing.JButton btnInicioRegistrarse;
    private javax.swing.JButton btnInicioSalir;
    private javax.swing.JComboBox<String> cbInicioTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtInicioContrasena;
    private javax.swing.JTextField txtInicioUsuario;
    // End of variables declaration//GEN-END:variables
}
