/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
//import Proyecto.ManejoArchivosTXT;

/**
 *
 * @author bloqu
 */
public class frmRegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistroUsuario
     */
    public frmRegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtRegistroUsuarioNombres1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistroUsuarioCrear = new javax.swing.JButton();
        txtRegistroUsuarioNombres = new javax.swing.JTextField();
        txtRegistroUsuarioNombreUsuario = new javax.swing.JTextField();
        txtRegistroUsuarioCorreo = new javax.swing.JTextField();
        txtRegistroUsuarioContrasena1 = new javax.swing.JTextField();
        txtRegistroUsuarioContrasena2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("Nombres");

        txtRegistroUsuarioNombres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroUsuarioNombres1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Crea una cuenta");

        jLabel2.setText("Nombres");

        jLabel3.setText("Correo Electronico");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Confirmar contraseña");

        btnRegistroUsuarioCrear.setText("Crear cuenta");
        btnRegistroUsuarioCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUsuarioCrearActionPerformed(evt);
            }
        });

        txtRegistroUsuarioNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroUsuarioNombresActionPerformed(evt);
            }
        });

        txtRegistroUsuarioNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroUsuarioNombreUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre de usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegistroUsuarioNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtRegistroUsuarioContrasena1)
                            .addComponent(txtRegistroUsuarioCorreo)
                            .addComponent(txtRegistroUsuarioContrasena2)
                            .addComponent(txtRegistroUsuarioNombres)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnRegistroUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRegistroUsuarioNombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistroUsuarioNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRegistroUsuarioCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRegistroUsuarioContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRegistroUsuarioContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistroUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        setSize(new java.awt.Dimension(398, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroUsuarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUsuarioCrearActionPerformed
    String nombres = txtRegistroUsuarioNombres.getText();
    String usuario = txtRegistroUsuarioNombreUsuario.getText();
    String correo = txtRegistroUsuarioCorreo.getText();
    String contrasena1 = txtRegistroUsuarioContrasena1.getText();
    String contrasena2 = txtRegistroUsuarioContrasena2.getText();
    String rutaProyecto = System.getProperty("user.dir");
    String dirTXT = rutaProyecto + "\\src\\texto\\registro_usuarios.txt";
    
    ManejoArchivosTXT crearVeri=new ManejoArchivosTXT();
    crearVeri.crearVer_Arch();
    
    if (nombres.isEmpty() || usuario.isEmpty() || correo.isEmpty() || contrasena1.isEmpty() || contrasena2.isEmpty()) 
    {
        JOptionPane.showMessageDialog(null, "Todos los espacios deben estar llenos", "Error de creación de cuenta",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean usuarioDuplicado = false;
    boolean correoDuplicado = false;

    try (BufferedReader lector = new BufferedReader(new FileReader(dirTXT))) 
    {
        String linea;
        while ((linea = lector.readLine()) != null) 
        {
            String[] bloques = linea.split(",");
            if (bloques.length == 5) 
            {
                String correoExistente = bloques[1];
                String usuarioExistente = bloques[2];

                if (correoExistente.equals(correo)) 
                {
                    correoDuplicado = true;
                }

                if (usuarioExistente.equals(usuario)) {
                    usuarioDuplicado = true;
                }
            }
        }
    } catch (IOException e) 
    {
        JOptionPane.showMessageDialog(null, "Error al leer el archivo de usuarios", "Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (correoDuplicado) 
    {
        JOptionPane.showMessageDialog(null, "El correo ya está registrado", "Error de creación de cuenta",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (usuarioDuplicado) 
    {
        JOptionPane.showMessageDialog(null, "El nombre de usuario ya está registrado", "Error de creación de cuenta",
                JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!contrasena1.equals(contrasena2)) 
    {
        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Error de creación de cuenta",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (FileWriter writer = new FileWriter(dirTXT, true)) 
    {
        writer.write("Usuario," + correo + "," + usuario + "," + contrasena1 + "," + nombres + "\n");
    } 
    catch (IOException e) 
    {
        JOptionPane.showMessageDialog(null, "Error al guardar la información en el archivo", "Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    JOptionPane.showMessageDialog(null, "La cuenta se ha creado con éxito", "Crear una cuenta",
            JOptionPane.INFORMATION_MESSAGE);

    frmPrincipal newFrame = new frmPrincipal();
    newFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegistroUsuarioCrearActionPerformed

    private void txtRegistroUsuarioNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroUsuarioNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroUsuarioNombresActionPerformed

    private void txtRegistroUsuarioNombres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroUsuarioNombres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroUsuarioNombres1ActionPerformed

    private void txtRegistroUsuarioNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroUsuarioNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroUsuarioNombreUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroUsuarioCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtRegistroUsuarioContrasena1;
    private javax.swing.JTextField txtRegistroUsuarioContrasena2;
    private javax.swing.JTextField txtRegistroUsuarioCorreo;
    private javax.swing.JTextField txtRegistroUsuarioNombreUsuario;
    private javax.swing.JTextField txtRegistroUsuarioNombres;
    private javax.swing.JTextField txtRegistroUsuarioNombres1;
    // End of variables declaration//GEN-END:variables
}
